### ISSUE TITLE
I can't find database setup scripts

### ISSUE THREAD

**Issue by magixsource** [acciente/oacc-core#17]
on page http://oaccframework.org/downloads.html , i  can't find it

**Comment by adinath-raveendraraj** [comment]
Thanks, for filing this issue, yes we do need to add to the database scripts to the download artifacts. In the meantime, the database scripts are available here: https://github.com/acciente/oacc-db

You can also access the scripts by release version on the above page under the Github "Releases". You can also simply use the version in master if your are using the latest release of OACC.

**Comment by magixsource** [comment]
:+1:  OK now : D

**Comment by fspinnenhirn** [comment]
Fixed - I just added the direct link for the [oacc-db](https://github.com/acciente/oacc-db) database setup scripts to the [downloads page](http://oaccframework.org/downloads.html) on _oaccframework.org_.
