### ISSUE TITLE
Update getting-started-tutorial.html

### ISSUE THREAD

**Issue by sebfz1** [acciente/oacc-core#19]
Hi,

The `getting-started-tutorial.html` is not up-to-date, the correct package in `rc4` is com.acciente.oacc.*sql*.SQLAccessControlSystemInitializer

```
$ java com.acciente.oacc.SQLAccessControlSystemInitializer -dburl=<db-url> \
>  -dbuser=<db-user> \
>  -dbpwd=<db-password> \
>  -oaccsystempwd=<OACC-root-password> \
>  [ -dbschema=<db-schema> ]   # [optional - omit if no database schema was created]
```

Thanks,
Sebastien.

**Comment by sebfz1** [comment]
Therefore the command line is not really accurate, it should likely be:
`java -cp acciente-oacc-2.0.0-rc.4-jdk1_7.jar com.acciente.oacc.sql.SQLAccessControlSystemInitializer -dburl=...`
or
`java -jar acciente-oacc-2.0.0-rc.4-jdk1_7.jar -dburl=...` (see #20)

**Comment by fspinnenhirn** [comment]
Thanks for pointing out the typo, Sebastien!
I'm on it.

**Comment by fspinnenhirn** [comment]
I just updated the tutorial and pushed the change to the live site.
