### ISSUE TITLE
OACC on Maven Central

### ISSUE THREAD

**Issue by mallim** [acciente/oacc-core#24]
Hi 

I noticed a thread discussing on OACC on Maven Central (https://groups.google.com/forum/#!topic/oacc-users/8nL6JeC8Xc0)

Just to create this issue to take note of the status.

Regards
Ian Lim

**Comment by adinath-raveendraraj** [comment]
OACC has now been setup to push to the Central Repository. The latest release v2.0.0-rc.6 is available at the following coordinates:

<dependency>
  <groupId>com.acciente.oacc</groupId>
  <artifactId>acciente-oacc</artifactId>
  <version>2.0.0-rc.6</version>
</dependency>
