### ISSUE TITLE
next release

### ISSUE THREAD

**Issue by JensPiegsa** [acciente/oacc-core#32]
OACC looks very promising, What are the plans for the next release? — Best Regards, Jens

**Comment by adinath-raveendraraj** [comment]
Thanks, Jens. We are currently wrapping up our work (in a feature branch) on making the password encryption scheme used by the built-in authentication module pluggable (as part of this we have added support for BCrypt as one of the available encryption schemes to use) -- we wanted to get this into the 2.0.0 release we are planning. As you can see in the feature branch, there are no changes to the main API exposed via the AccessControlContext interface for these enhancements.

There has been interest expressed in final 2.0.0 release, so we are planning to publish it in the first half of this year.  We are also close to publishing a fully working tutorial that shows an application secured using OACC.

**Comment by JensPiegsa** [comment]
Hi Adinath. That's actually great news. Thanks for providing these insights on your current work. I was just a little concerned as the last release candidate on Maven Central has been back a while. I'll give OACC a test run. — Jens
