### ISSUE TITLE
Question - Can roles/perms can be inherited ?

### ISSUE THREAD

**Issue by thealchemistt** [acciente/oacc-core#50]
Say if there are 2 users one with READ and another with WRITE permission. Then can the user with WRITE permission READ the given resource/document also?

In addition to that, the secure-todo example is sharing items to another user hence giving the access to it.
Can't we assign the same permissions to a new user with which an existing user created a resource and this new user can directly access this given the fact that both the users have same permissions? Is this possible.

**Comment by adinath-raveendraraj** [comment]
Hi Yagnesh,

I answered this on your cross-post in the OACC user group here: https://groups.google.com/g/oacc-users/c/llIYSOTxy9o

Thanks,
Adi
